name: 'Setup OpenGauss database'
description: 'Setup a OpenGauss database'
author: 'namo'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  # See https://hub.docker.com/r/enmotech/opengauss for supported versions
  # and further details on input environment variables
  GS_VERSION:
    description: 'Version of Opengauss to use'
    required: false
    default: 'latest'
  GS_USERNAME:
    description: 'GS_USERNAME - create the specified user with superuser power'
    required: false
    default: ''
  GS_PASSWORD:
    description: 'GS_PASSWORD - superuser password'
    required: true
    default: 'Gauss@123'
runs:
  using: 'docker'
  image: 'Dockerfile'
